### ISSUE TITLE
Duplicate Email Bug

### ISSUE THREAD

**Issue by nikhilbhatt** [nikhilbhatt/EmailValidator#70]
Fix the following
1. When a user checks for the validity of an email more than one time than duplicate emails are saving in the database.
2. Restrict the JSON content to frontend

**Comment by maniSHarma7575** [comment]
@nikhilbhatt try to remove bug for true mailer.

**Comment by nikhilbhatt** [comment]
@maniSHarma7575  do we need to run `gem install truemail` in CI explicitly?
